"""empty message

Revision ID: 3eeccf6ff8d1
Revises: be6fb5724cf9
Create Date: 2025-08-11 12:34:27.285816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3eeccf6ff8d1'
down_revision = 'be6fb5724cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_constraint('comentario_ibfk_2', type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('comentario_ibfk_2', 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###
